CHOICES = {
    "collection": ["cmip6", "cordex"],
    "activity_id": ["ScenarioMIP", "CMIP"],
    "cf_standard_name": [
        "air_temperature",
        "precipitation_flux",
        "surface_downwelling_shortwave_flux_in_air",
        "specific_humidity",
        "snowfall_flux",
        "surface_downwelling_longwave_flux_in_air",
        "eastward_wind",
        "northward_wind",
        "surface_upwelling_shortwave_flux_in_air",
        "air_pressure_at_mean_sea_level",
    ],
    "data_specs_version": [
        "01.00.30",
        "01.00.29",
        "01.00.31",
        "01.00.27",
        "01.00.21",
        "01.00.28",
        "01.00.23",
        "01.00.32",
        "01.00.33",
    ],
    "experiment_id": ["historical", "ssp245", "ssp585", "ssp126", "ssp119"],
    "experiment_title": [
        "all-forcing simulation of the recent past",
        "update of RCP4.5 based on SSP2",
        "update of RCP8.5 based on SSP5",
        "update of RCP2.6 based on SSP1",
        "low-end scenario reaching 1.9 W m-2, based on SSP1",
        "Simulation of recent past (1850 to 2014). Impose changing conditions (consistent with observations). Should be initialised from a point early enough in the pre-industrial control run to ensure that the end of all the perturbed runs branching from the end of this historical run end before the end of the control. Only one ensemble member is requested but modelling groups are strongly encouraged to submit at least three ensemble members of their CMIP historical simulation.",
        "historical",
        "SSP-based RCP scenario with medium radiative forcing by the end of the century.  Following approximately RCP4.5 global forcing pathway with SSP2 socioeconomic conditions. Radiative forcing reaches a level of 4.5 W/m2 in 2100. Concentration-driven.",
        "all-forcing simulation of the recent past",
        "SSP-based RCP scenario with high radiative forcing by the end of century. Following approximately RCP8.5 global forcing pathway with SSP5 socioeconomic conditions. Concentration-driven.",
    ],
    "frequency": ["mon", "day", "3hr", "3hrPt", "monC"],
    "grid": [
        "gn",
        "native atmosphere regular grid",
        "Native N96 grid; 192 x 144 longitude/latitude",
        "data regridded to a T127 gaussian grid (128x256 latlon) from a native atmosphere T127l reduced gaussian grid",
        "gs1x1",
        "T255L91",
        "LMDZ grid",
        "gs2x1.5",
        "T63L49 native atmosphere, T63 Linear Gaussian Grid; 128 x 64 longitude/latitude; 49 levels; top level 1 hPa",
        "T106",
    ],
    "grid_label": ["gn", "gr", "gr1"],
    "institution_id": [
        "EC-Earth-Consortium",
        "MOHC",
        "CNRM-CERFACS",
        "CMCC",
        "MIROC",
        "IPSL",
        "NOAA-GFDL",
        "CAS",
        "INM",
        "MPI-M",
    ],
    "mip_era": ["CMIP6"],
    "nominal_resolution": ["100 km", "250 km", "500 km", "50 km", "10000 km", "10 km"],
    "source_id": [
        "IPSL-CM6A-LR",
        "UKESM1-0-LL",
        "MIROC6",
        "HadGEM3-GC31-LL",
        "ACCESS-CM2",
        "CMCC-ESM2",
        "MPI-ESM1-2-LR",
        "GFDL-ESM4",
        "MPI-ESM1-2-HR",
        "CNRM-ESM2-1",
    ],
    "source_type": [
        "AOGCM",
        "AOGCM AER",
        "AOGCM BGC",
        "AOGCM AER BGC",
        "AOGCM BGC AER CHEM",
        "AOGCM AER CHEM",
        "AOGCM AER BGC CHEM",
        "AOGCM AER CHEM BGC",
        "AOGCM BGC AER",
        "AOGCM BGC CHEM AER",
    ],
    "sub_experiment_id": ["none"],
    "table_id": ["Amon", "day", "3hr", "E3hr", "CF3hr"],
    "variable_id": [
        "pr",
        "tas",
        "rsds",
        "huss",
        "prsn",
        "rlds",
        "uas",
        "vas",
        "psl",
        "rsus",
    ],
    "variable_long_name": [
        "Precipitation",
        "Near-Surface Air Temperature",
        "Surface Downwelling Shortwave Radiation",
        "Near-Surface Specific Humidity",
        "Snowfall Flux",
        "Surface Downwelling Longwave Radiation",
        "Sea Level Pressure",
        "Surface Upwelling Shortwave Radiation",
        "Surface Upwelling Longwave Radiation",
        "Eastward Near-Surface Wind",
    ],
    "variable_units": ["W m-2", "m s-1", "K", "kg m-2 s-1", "%", "1", "Pa", "kg m-2"],
    "variant_label": ["r1i1p1f1", "r1i1p1f2", "r1i1p1f3", "r1i1p2f1", "r1i1000p1f2"],
}
