name: esgf-playground-utils

on:
  push:
    paths:
      - 'esgf-playground-utils/**'
  pull_request:
    paths:
      - 'esgf-playground-utils/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run black
        run: |
          cd esgf-playground-utils
          pip install poetry
          poetry install --with black
          poetry run black --check