---
name: Tox

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
        py:
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
      - name: Install test dependencies.
        run: python -m pip install 'tox>=4.0.16' 'tox-gh' 'urllib3<2'
      - name: Run test suite
        run: tox run
